analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.05725446
title: Colorado Trip 2016
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.04837115
  brandStrength: 0.1022758
  rhythmicContrast: 0.2772201
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.8475565
purpose: []
favicon: null
name: Colorado 2016
typography_spectrum: 0.5313157
