layout_spectrum: 0.05725446
typography_spectrum: 0.5313157
color:
  saturation: 0.04837115
  lightness: 0.8475565
  brandStrength: 0.1022758
  rhythmicContrast: 0.2772201
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Colorado 2016
